### ISSUE TITLE
Release of weights

### ISSUE THREAD

**Issue by YifanDengWHU** [HeliXonProtein/OmegaFold#1]
Hi, thanks for the great work!
I have been waiting OmegaFold for a long time and deployed it in our research the first day when the code is released. And I wonder when will the weights be available? It will benefit our research greatly. Thank you so much for your work!

**Comment by RuiWang1998** [comment]
Hi,

Thanks for your interest in our work! The weight is releasing in a matter of days or hours if we are lucky! Stay tuned!

Best.
