### ISSUE TITLE
3Dprojection?

### ISSUE THREAD

**Issue by ZKRwestlake** [HeliXonProtein/OmegaFold#11]
I can't find 3Dprojection or edge update in the structure module as described in the paper. Have I missed it or is it yet to be released?

**Comment by mooninrain** [comment]
Hi, 

Thanks for your great attention and reply!

The current model1 does not contain these modules, and we add these features later in other ensemble models.

We are working hard on optimizing memory and speed currently. Ensemble code and models will be released a little bit later.

Thank you for your patience, please stay tuned!

**Comment by CeciLyu** [comment]
Hi OmegaFold Team,

The current priority makes sense! Just out of curiosity, do you have any data on the prediction quality for the current version of the model?

Thanks

**Comment by ZKRwestlake** [comment]
> Hi,
> 
> Thanks for your great attention and reply!
> 
> The current model1 does not contain these modules, and we add these features later in other ensemble models.
> 
> We are working hard on optimizing memory and speed currently. Ensemble code and models will be released a little bit later.
> 
> Thank you for your patience, please stay tuned!

Thanks for your reply! Looking forward to further releases.
