### ISSUE TITLE
pseudo MSAs in OmegaPLM

### ISSUE THREAD

**Issue by BSharmi** [HeliXonProtein/OmegaFold#34]
Hi,

I noticed OmegaFold help mentions about an Examples folder which is missing in the rep. Is it going to be added sometime so we can access results from individual modules (PLM, GeoFormer and Struct). 
I am interested to get embeddings from any trained language model and I hacked the code for now to the same. But I am not sure why pseudo MSAs are needed. I do not remember seeing them in the paper. 
Can I just use embeddings from any trained model and feed those to the GeoFormer and Struct modules?
Also it would be helpful if some comments are added in the config file (such as alphabet size which is used twice with different values).

Thank you!

**Comment by RuiWang1998** [comment]
> I noticed OmegaFold help mentions about an Examples folder which is missing in the rep. Is it going to be added sometime so we can access results from individual modules (PLM, GeoFormer and Struct).

Yes we forgot about this one. We are going to add this soon.
> I am interested to get embeddings from any trained language model and I hacked the code for now to the same. But I am not sure why pseudo MSAs are needed. I do not remember seeing them in the paper.

They are not extremely important, but gives a minor boost so we did not mention it.
> Can I just use embeddings from any trained model and feed those to the GeoFormer and 
Struct modules?

You could definitely try and we think it is very possible that they will work.

>Also it would be helpful if some comments are added in the config file (such as alphabet size which is used twice with different values).
Sure will do!
