### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by biotech70** [HeliXonProtein/OmegaFold#37]
During running Omegafold in ubuntu 22.04 (RAM= 16 G, Cpu= i7-6700K, GPU= GTX 750 Ti), I got the following error for a peptide with 8 residues.
![error](https://user-images.githubusercontent.com/73783725/189525579-99adbaf6-800c-443e-9c2a-bfc5dff027ff.png)

**Comment by RuiWang1998** [comment]
Hi,

Unfortunately it might be not possible to run the model on a 2GB-ram card. You could try to set `--subbatch_size` to 1 and see if it runs. If it does not run and output the same error stack, then we suggest you get access to a larger card (through colab, for example).

Best
