### ISSUE TITLE
Confidence metric 

### ISSUE THREAD

**Issue by Geraldene** [HeliXonProtein/OmegaFold#46]
Is the confidence metric computed in the B-factor column similar to the LDDT score? I have predicted structures using Omegafold and Alphafold and the values I get for the Alphafold are always >70% for natural sequences whereas for structures predicted with Omegafold the "confidence metric" is much lower most values lie between ~20-60. Please can you provide further clarification?

**Comment by universvm** [comment]
Why did you close this? Did you solve the issue?

**Comment by Geraldene** [comment]
Yes I have, you can use the B-factor column to calculate the confidence score

**Comment by DrLeucine** [comment]
yes but what does the actual value mean and does it range from 0 - 100 ?

**Comment by Geraldene** [comment]
You want to get the mean of the column and yes it does range from 0-100. The value corresponds to a similar metric used by Alphafold known as the pLDDT score(the higher the score the more confidence you have in the prediction).
 "To this end, AlphaFold produces a per-residue confidence metric called predicted local distance difference test (pLDDT) on a scale from 0 to 100. pLDDT estimates how well the prediction would agree with an experimental structure based on the local distance difference test Cα (lDDT-Cα"
