### ISSUE TITLE
AttributeError: module 'os' has no attribute 'pathconf'

### ISSUE THREAD

**Issue by saurabhgayali** [HeliXonProtein/OmegaFold#7]
AFter installation When I am running, following error is happening:

```
INFO:root:Loading weights from C:\Users\User/.cache/omegafold_ckpt/model.pt
INFO:root:Constructing OmegaFold
INFO:root:Reading ../SECRETFOLDER/sequences.fasta
Traceback (most recent call last):
  File "L:\Omegafold\OmegaFold\main.py", line 105, in <module>
    main()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "L:\Omegafold\OmegaFold\main.py", line 58, in main
    for i, (input_data, save_path) in enumerate(
  File "L:\Omegafold\OmegaFold\pipeline.py", line 132, in fasta2inputs
    name_max = os.pathconf(output_dir, 'PC_NAME_MAX') - 4
AttributeError: module 'os' has no attribute 'pathconf'

```
![image](https://user-images.githubusercontent.com/13806535/182962958-6f4be0b1-0c62-42a0-a01e-e0e87465d323.png)

OS Windows 10
Python: 3.10.7
PIP: 22.2.2

**Comment by RuiWang1998** [comment]
Hi!

Thanks for checking out our model! This issue exists because currently we are not supporting Windows officially, but it is going to be supported in a couple of days.

For the time being, you can clone the repository, `gh pr checkout 3`, which takes you to #5 that supports Windows and should get you where you want.

**Comment by saurabhgayali** [comment]
Found it somewhere on Stackoverflow.
Hardcoded name_max  to 100
`name_max =100`
and now it is working

Something Python should work on.

**Comment by RuiWang1998** [comment]
Great! That's a workaround for now, the update is on the way!

**Comment by RuiWang1998** [comment]
Hi

We think we have fixed this with the latest update, so we'll close this issue for now.
